// PROVINCE
export const PROVINCE_REQUEST = 'PROVINCE_REQUEST';
export const GET_LIST_PROVINCE = 'GET_LIST_PROVINCE';
export const GET_PROVINCE_SELECTED = 'GET_PROVINCE_SELECTED';

// DISTRICT
export const DISTRICT_REQUEST = 'DISTRICT_REQUEST';
export const GET_LIST_DISTRICT = 'GET_LIST_DISTRICT';
export const GET_DISTRICT_SELECTED = 'GET_DISTRICT_SELECTED';

// MOTEL
export const MOTEL_REQUEST = 'MOTEL_REQUEST';
export const GET_MOTEL_DATA = 'GET_MOTEL_DATA';
export const GET_MOTEL_ITEM_DATA = 'GET_MOTEL_ITEM_DATA';
export const RESET_MOTEL_DATA = 'RESET_MOTEL_DATA'
export const ITEM_HOVER = 'ITEM_HOVER';
export const ON_MOUSE_OUT = 'ON_MOUSE_OUT';
export const GET_MOTEL_BY_PROVINCE = 'GET_MOTEL_BY_PROVINCE';
export const GET_MOTEL_BY_DISTRICT = 'GET_MOTEL_BY_DISTRICT';
export const FILLTER_RESET = 'FILLTER_RESET';

// USER
export const USER_REQUEST = 'USER_REQUEST';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOCAL = 'USER_LOCAL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER = 'USER_REGISTER';